### ISSUE TITLE
[NumberGuesser] Properties

### ISSUE THREAD

**Issue by pavel-b-novikov** [amakalev/nsudotnet#1]
Куда дели директорию Properties? Что в ней лежит и зачем оно надо?

**Comment by amakalev** [comment]
В ней лежат параметры конфигурации, применяемые ко всему проекту, к примеру, параметры компиляции.

**Comment by pavel-b-novikov** [comment]
Это какие такие параметры компиляции лежат в Properties? Флаги оптимизации для компилятора?

**Comment by amakalev** [comment]
Информация о сборке(AssemblyInfo, версия, GUID, ...), файлы ресурсов(по умолчанию), параметры для запуска(например, аргументы командной строки)

**Comment by pavel-b-novikov** [comment]
Аргументы командной строки?
Андрей, выше тройки я вам поставить не могу. Давайте завершим этот разговор.

**Comment by amakalev** [comment]
![screenshot 4](https://cloud.githubusercontent.com/assets/22714879/26526389/768ce3bc-43a3-11e7-9593-a6f8161eebf8.png)

**Comment by amakalev** [comment]
![screenshot 5](https://cloud.githubusercontent.com/assets/22714879/26526395/a99c065c-43a3-11e7-9047-98f3585cb2d6.png)

**Comment by amakalev** [comment]
Если разговор окончен, я не буду тратить время на доделывание еще одной задачи

**Comment by pavel-b-novikov** [comment]
Этот файл появляется в случае разработки под .NET Core. И он определяет не "аргументы командной строки", а конфигурацию среды запуска и включает в себя переменные окружения, параметры развертывания приложения вплоть до того какой браузер открыть для просмотра, что особенно актуально для OWIN и ASP.NET Core. Как у вас создался launchsettings в консольном приложении и нахрена он вам там - я просто ума не приложу. Но вы даже не додумались этот файл закоммитить. Я уже не говорю о том, чтобы забить в гугл и посмотреть что оно делает.

**Comment by pavel-b-novikov** [comment]
4 в зачетку, но бога ради, не пишите следующую задачу
