### ISSUE TITLE
[NumberGuesser] Префиксный инкремент/декремент

### ISSUE THREAD

**Issue by pavel-b-novikov** [amakalev/nsudotnet#3]
Приведите пример кода, поведение которого будет меняться в зависимости от типа инкремента или декремента

**Comment by amakalev** [comment]
Не вижe какой-либо проблемы в префиксных инкрементах, по-моему, это дело вкуса, да и привычка с c++

**Comment by pavel-b-novikov** [comment]
Вы хорошо прочитали issue?

**Comment by amakalev** [comment]
окей:
1) arr[i++] = 10;
2) arr[++i] = 10;
