### ISSUE TITLE
[Enigma] Ффйл ключа

### ISSUE THREAD

**Issue by pavel-b-novikov** [amakalev/nsudotnet#5]
```File.Open("key.txt"...)```

Где в итоге окажется результирующий файл ключа?

**Comment by amakalev** [comment]
при таком вызове файл ключа окажется в директории, в которой был запущен .exe (относительный путь)

**Comment by pavel-b-novikov** [comment]
Ответ правильный лишь в ряде случаев. Пожалуйста, точнее

**Comment by amakalev** [comment]
Зависит от переменной среды PWD

**Comment by pavel-b-novikov** [comment]
![image](https://cloud.githubusercontent.com/assets/2521412/26523563/71645208-4344-11e7-93b7-370f5c58bedb.png)

**Comment by amakalev** [comment]
working directory?

**Comment by pavel-b-novikov** [comment]
Странно что мы пришли к этому ответу спустя 5 сообщений и при посредничестве Михаила.
